var template = require('./templates');

exports.all = [
    { role: "Wolf man", value: -9, amount: 1, templates: template.none },
    { role: "Big Bad Wolf", value: -9, amount: 1, templates: template.wolfpack },
    { role: "Wolf Cub", value: -8, amount: 1, templates: template.amateur + template.wolfpack + template.competent },
    { role: "Vampire", value: -7, amount: 8, templates: template.none },
    { role: "Bogeyman", value: -6, amount: 1, templates: template.none },
    { role: "Minion", value: -6, amount: 1, templates: template.competent },
    { role: "Werewolf", value: -6, amount: 12, templates: template.all },
    { role: "Dream Wolf", value: -5, amount: 1, templates: template.wolfpack },
    { role: "Lone Wolf", value: -4, amount: 1, templates: template.wolfpack },
    { role: "Fruit Brute", value: -3, amount: 1, templates: template.wolfpack },
    { role: "Sorcerer", value: -3, amount: 1, templates: template.competent },
    { role: "Cursed", value: -3, amount: 1, templates: template.competent },
    { role: "Count Dracula", value: -2, amount: 1, templates: template.none },
    { role: "Cupid", value: -2, amount: 1, templates: template.competent },
    { role: "Doppelgänger", value: -2, amount: 1, templates: template.competent },
    { role: "Sasquatch", value: -2, amount: 1, templates: template.none },
    { role: "Lycan", value: -1, amount: 1, templates: template.competent },
    { role: "Pacifist", value: -1, amount: 1, templates: template.none },
    { role: "Old Man", value: 0, amount: 1, templates: template.none },
    { role: "Hoodlum", value: 0, amount: 1, templates: template.none },
    { role: "Little Girl", value: 0, amount: 1, templates: template.none },
    { role: "Wild Child", value: 0, amount: 1, templates: template.competent },
    { role: "Moderator", value: 0, amount: 1, templates: template.none },
    { role: "Villager", value: 1, amount: 20, templates: template.all },
    { role: "Old Hag", value: 1, amount: 1, templates: template.none },
    { role: "Cult leader", value: 1, amount: 1, templates: template.competent },
    { role: "Spellcaster", value: 1, amount: 1, templates: template.competent },
    { role: "Tanner", value: 1, amount: 1, templates: template.amateur + template.competent },
    { role: "Bloody Mary", value: 1, amount: 1, templates: template.none },
    { role: "Nostradamus", value: 1, amount: 1, templates: template.none },
    { role: "Beeholder", value: 2, amount: 1, templates: template.none },
    { role: "Ghost", value: 2, amount: 1, templates: template.none },
    { role: "Village Idiot", value: 2, amount: 1, templates: template.none },
    { role: "Mason", value: 2, amount: 3, templates: template.competent },
    { role: "Mayor", value: 2, amount: 1, templates: template.all - template.novice },
    { role: "Troublemaker", value: 2, amount: 1, templates: template.none },
    { role: "Bodyguard", value: 3, amount: 1, templates: template.competent },
    { role: "Diseased", value: 3, amount: 1, templates: template.competent },
    { role: "Hunter", value: 3, amount: 1, templates: template.none },
    { role: "Insomniac", value: 3, amount: 1, templates: template.none },
    { role: "Martyr", value: 3, amount: 1, templates: template.wolfpack },
    { role: "P.I.", value: 3, amount: 1, templates: template.none },
    { role: "Priest", value: 3, amount: 1, templates: template.none },
    { role: "Prince", value: 3, amount: 1, templates: template.amateur + template.wolfpack + template.competent },
    { role: "Tough Guy", value: 3, amount: 1, templates: template.none },
    { role: "Thing", value: 3, amount: 1, templates: template.none },
    { role: "Drunk", value: 3, amount: 1, templates: template.competent },
    { role: "Apprentice Seer", value: 4, amount: 1, templates: template.competent },
    { role: "Witch", value: 4, amount: 1, templates: template.amateur + template.competent },
    { role: "Chupacabra", value: 4, amount: 1, templates: template.none },
    { role: "The Count", value: 5, amount: 1, templates: template.none },
    { role: "Leprechaun", value: 5, amount: 1, templates: template.none },
    { role: "Seer", value: 7, amount: 1, templates: template.all - template.basic }
];