exports.default = {
    'Apprentice Seer': '*Apprentice Seer, open your eyes.',    
    'Aura Seer': 'Aura Seer open your eyes, check a player.',
    'Beholder': 'Beholder open your eyes, (point the player) this is the village seer.',
    'Big Bad Wolf': '*Big Bad Wolf, open your eyes.',
    'Bloody Mary': '(When she is already dead), choose a player to kill.',
    'Bodyguard': 'Wake up Bodyguard, choose a player to protect.',
    'Bogeyman': '(If wolves didn\'t kill) Bogeyman wake up, choose a player to kill.',
    'Chupacabra': 'Chupacabra wake up, choose a player.',
    'Count Dracula': 'Dracula, open your eyes and pick a wife.',
    'Cult Leader': 'Cultists, open your eyes, who\'s gonna be converted tonight?',
    'Cupid': '*Wake up Cupid, choose the lovebirds.',
    'Cursed': '*Cursed, open your eyes',
    'Dire Wolf': '*Wake up Dire Wolf, choose your companion.',
    'Diseased': '*Diseased, open your eyes.',
    'Doppelgänger': '*Doppelgänger, open your eyes, choose your role model.',
    'Drunk': '(Third night), open your eyes, give him his new role.',
    'Fortune Teller': 'Fortune Teller, check a player.',
    'Fruit Brute': 'Fruit Brute open your eyes.',
    'Hoodlum': '*Wake up Hoodlum, choose 2 players.',
    'Hunter': '*Hunter, open your eyes.',
    'Insomniac': 'Insomniac, there have been activity around you (tell with hands).',
    'Leprechaun': 'Leprechaun open your eyes, (point the player) this player have been killed, will you redirect the attack?',
    'Lovebirds': '*Lovebirds meet each other.',
    'Lycan': '*lycan, open your eyes.',
    'Mason': '*Masons, open your eyes and look for other Masons.',
    'Meeting': 'Masons, open your eyes it\'s meeting time.',
    'Minion': '*Minion, you are part of the (moderator choose vampires or werewolves) team.',
    'Nostradamus': '*Nostradamus, open your eyes, predict the winning team.',
    'Old Hag': 'Old Hag open your eyes, who must leave the village next day?',
    'P.I.': 'Private Investigator wake up, inspect a player and his neighbors.',
    'Priest': 'Priest, for whom do you pray?',
    'Seer': 'Wake up seer, check a player.',
    'Sorcerer': '(Until found a werewolf, after that join wolves and ask before they choose) wake up sorcerer, point at a player.',
    'Spellcaster': 'Spellcaster, who must not use their voice the following day?',
    'The Count': '*The Count, there is (show with hands) wolves in this side of the village and (show with hands) in the other side.',
    'Thing': 'Thing, tap a player next to you.',
    'Tough Guy': '*Tough Guy, wake up.',
    'Vampire': 'Vampires, *(open your eyes and look for other vampires.), choose a player to kill.',
    'Werewolves': 'Werewolves, *(open your eyes and look for other werewolves.), choose a player to kill.',
    'Wild Child': '*Wild Child, choose your role model.',
    'Witch': 'Witch open your eyes, (point the player) this player have been killed, do you want to revive him? (one per game), do you want to kill someone else? (one per game).',
    'Wolf Man': '*Wolf man wake up.',
    'Wolverine': '*Wolverine, open your eyes.'
}