exports.english = {
    'Cupid': '*Wake up Cupid, choose the lovebirds.',
    'Lovebirds': '*Lovebirds meet each other.',
    'Doppelgänger': '*Doppelgänger, open your eyes, choose your role model.',
    'Hoodlum': '*Wake up Hoodlum, choose 2 players.',
    'Wild Child': '*Wild Child, choose your role model.',
    'Dire Wolf': '*Wake up Dire Wolf, choose your companion.',
    'Nostradamus': '*Nostradamus, open your eyes, predict the winning team.',
    'Wolf Man': '*Wolf man wake up.',
    'Fruit Brute': 'Fruit Brute open your eyes.',
    'Lycan': '*lycan, open your eyes.',
    'Apprentice Seer': '*Apprentice Seer, open your eyes.',    
    'Mason': '*Masons, open your eyes and look for other Masons.',
    'Meeting': 'Masons, open your eyes it\'s meeting time.',
    'Thing': 'Thing, tap a player next to you.',
    'Bodyguard': 'Wake up Bodyguard, choose a player to protect.',
    'Priest': 'Priest, for whom do you pray?',
    'Cult Leader': 'Cultists, open your eyes, who\'s gonna be converted tonight?',
    'Count Dracula': 'Dracula, open your eyes and pick a wife.',
    'Sorcerer': '(Until found a werewolf, after that join wolves and ask before they choose) wake up sorcerer, point at a player.',
    'Vampire': 'Vampires, *(open your eyes and look for other vampires.), choose a player to kill.',
    'Minion': 'Minion, you are part of the (moderator choose vampires or werewolves) team.',
    'Werewolves': 'Werewolves, *(open your eyes and look for other werewolves.), choose a player to kill.',
    'Leprechaun': 'Leprechaun open your eyes, (point the player) this player have been killed, will you redirect the attack?',
    'Bogeyman': '(If wolves didn\'t kill) Bogeyman wake up, choose a player to kill.',
    'Bloody Mary': '(When she is already dead), choose a player to kill.',
    'Chupacabra': 'Chupacabra wake up, choose a player.',
    'Witch': 'Witch open your eyes, (point the player) this player have been killed, do you want to revive him? (one per game), do you want to kill someone else? (one per game).',
    'Beholder': 'Beholder open your eyes, (point the player) this is the village seer.',
    'Seer': 'Wake up seer, check a player.',
    'Aura Seer': 'Aura Seer open your eyes, check a player.',
    'Fortune Teller': 'Fortune Teller, check a player.',
    'The Count': '*The Count, there is (show with hands) wolves in this side of the village and (show with hands) in the other side.',
    'Insomniac': 'Insomniac, there have been activity around you (tell with hands).',
    'P.I.': 'Private Investigator wake up, inspect a player and his neighbors.',
    'Old Hag': 'Old Hag open your eyes, who must leave the village next day?',
    'Spellcaster': 'Spellcaster, who must not use their voice the following day?',
    'Tough Guy': 'Tough Guy, wake up.',
    'Hunter': '*Hunter, open your eyes.',
    'Diseased': '*Diseased, open your eyes.',
    'Big Bad Wolf': '*Big Bad Wolf, open your eyes.',
    'Wolverine': '*Wolverine, open your eyes.',
    'Cursed': '*Cursed, open your eyes',
}