exports.english = {
    'Apprentice Seer': '*Apprentice Seer, open your eyes.',    
    'Aura Seer': 'Aura Seer open your eyes, check a player.',
    'Beholder': 'Beholder open your eyes, (point the player) this is the village seer.',
    'Big Bad Wolf': '*Big Bad Wolf, open your eyes.',
    'Bloody Mary': '(When she is already dead), choose a player to kill.',
    'Bodyguard': 'Wake up Bodyguard, choose a player to protect.',
    'Bogeyman': '(If wolves didn\'t kill) Bogeyman wake up, choose a player to kill.',
    'Chupacabra': 'Chupacabra wake up, choose a player.',
    'Count Dracula': 'Dracula, open your eyes and pick a wife.',
    'Cult Leader': 'Cultists, open your eyes, who\'s gonna be converted tonight?',
    'Cupid': '*Wake up Cupid, choose the lovebirds.',
    'Cursed': '*Cursed, open your eyes',
    'Dire Wolf': '*Wake up Dire Wolf, choose your companion.',
    'Diseased': '*Diseased, open your eyes.',
    'Doppelgänger': '*Doppelgänger, open your eyes, choose your role model.',
    'Drunk': '(Third night), open your eyes, give him his new role.',
    'Fortune Teller': 'Fortune Teller, check a player.',
    'Fruit Brute': '*Fruit Brute, open your eyes.',
    'Hoodlum': '*Wake up Hoodlum, choose 2 players.',
    'Hunter': '*Hunter, open your eyes.',
    'Insomniac': 'Insomniac, there have been activity around you (tell with hands).',
    'Leprechaun': 'Leprechaun open your eyes, (point the player) this player have been killed, will you redirect the attack?',
    'Lovebirds': '*Lovebirds meet each other.',
    'Lycan': '*Lycan, open your eyes.',
    'Mason': '*Masons, open your eyes and look for other Masons.',
    'Meeting': 'Masons, open your eyes it\'s meeting time.',
    'Minion': '*Minion, you are part of the (moderator choose vampires or werewolves) team.',
    'Nostradamus': '*Nostradamus, open your eyes, predict the winning team.',
    'Old Hag': 'Old Hag open your eyes, who must leave the village next day?',
    'P.I.': 'Private Investigator wake up, inspect a player and his neighbors.',
    'Priest': 'Priest, for whom do you pray?',
    'Seer': 'Wake up Seer, check a player.',
    'Sorcerer': '(Until found a werewolf, after that join wolves and ask before they choose) wake up sorcerer, point at a player.',
    'Spellcaster': 'Spellcaster, who must not use their voice the following day?',
    'The Count': '*The Count, there is (show with hands) wolves in this side of the village and (show with hands) in the other side.',
    'Thing': 'Thing, tap a player next to you.',
    'Tough Guy': '*Tough Guy, wake up.',
    'Vampire': 'Vampires, *(open your eyes and look for other vampires.), choose a player to kill.',
    'Werewolves': 'Werewolves, *(open your eyes and look for other werewolves.), choose a player to kill.',
    'Wild Child': '*Wild Child, choose your role model.',
    'Witch': 'Witch open your eyes, (point the player) this player have been killed, do you want to revive him? (one per game), do you want to kill someone else? (one per game).',
    'Wolf Man': '*Wolf Man wake up.',
    'Wolverine': '*Wolverine, open your eyes.'
}

exports.spanish = {
    'Apprentice Seer': '*Aprendiz Vidente (Apprentice Seer), abre tus ojos.',    
    'Aura Seer': 'Vidente Aura (Aura Seer) levántate, verifica un jugador.',
    'Beholder': 'Espectador (Beholder) abre tus ojos, (señala al jugadr) este es el Vidente de la aldea.',
    'Big Bad Wolf': '*Lobo Feroz (Big Bad Wolf), abre tus ojos.',
    'Bloody Mary': '(Cuando ya está muerta), seleciona a quien matarás.',
    'Bodyguard': 'levántate Escolta (Bodyguard), elige a quien vas a resguardar.',
    'Bogeyman': '(Si los lobos no mataron!) Se levanta El Cuco (Bogeyman), elige a quien matar.',
    'Chupacabra': 'Se levanta el Chupacabra, selecciona un jugador.',
    'Count Dracula': 'Dracula, abre tus ojos y escoge a tu esposa.',
    'Cult Leader': 'Cultistas (Cultists), abran sus ojos, a quién van a incluir al culto?',
    'Cupid': '*Se levanta Cupido (Cupid), elige a los enamorados.',
    'Cursed': '*Maldito (Cursed), abre tus ojos.',
    'Dire Wolf': '*Se levanta el Lobo Gigante (Dire Wolf), selecciona su compañía.',
    'Diseased': '*Enfermo (Diseased), abre tus ojos.',
    'Doppelgänger': '*Doppelgänger, abre tus ojos, selecciona tu modelo a seguir.',
    'Drunk': '(Tercera noche), Borracho (Drunk) abre tus ojos, recibe tu nuevo rol.',
    'Fortune Teller': 'Adivino (Fortune Teller), verifica un jugador.',
    'Fruit Brute': '*Fruit Brute, abre tus ojos.',
    'Hoodlum': '*Despierta Matón (Hoodlum), elige a 2 jugadores.',
    'Hunter': '*Cazador (Hunter), abre tus ojos.',
    'Insomniac': 'Insomne (Insomniac), ha habido actividad a tu alrededor (indicarlo con las manos).',
    'Leprechaun': 'Duende (Leprechaun) abre tus ojos, (apunta al jugador) ha sido asesinado, vas a reorientar su muerte?',
    'Lovebirds': '*enamorados, hora de conocerse.',
    'Lycan': '*Licántropo (Lycan), abre tus ojos.',
    'Mason': '*Masones (Masons), abran sus ojos y conozcan los otros masones.',
    'Meeting': 'Masones, es hora de su reunión.',
    'Minion': '*Lacayo (Minion), servirás a los (el moderador elige vampiros o lobos).',
    'Nostradamus': '*Nostradamus, derpierta, predice el equipo ganador.',
    'Old Hag': 'Vieja Arpía (Old Hag) despierta, quién no será parte de la villa durante el día?',
    'P.I.': 'Despierta Investigador Privado (P.I.), inspecciona un jugador y sus vecinos.',
    'Priest': 'Cura, por quién rezarás?',
    'Seer': 'Se levante el Vidente (Seer), verifica un jugador.',
    'Sorcerer': '(Hasta que encuentre un lobo, luego se une a la manada y consutla antes de que los lobos seleccionen) Despierta Hechicra (Sorcerer), apunta a un jugador.',
    'Spellcaster': 'Conjurador (Spellcaster), quién no podrá usar su voz durante el día?',
    'The Count': '*Contador (The Count), la aldea ha sido invadida por (indicar la cantidad con las manos) lobos en esta parte y (indicar con las manos) en esta otra.',
    'Thing': 'Mañoso (Thing), toca un jugador a tu alrededor.',
    'Tough Guy': '*Tipo Rudo (Tough Guy), abre tus ojos.',
    'Vampire': 'Vampiros (Vampires), *(abran sus ojos y miren los demás vampiros.), seleccionen a quien matar.',
    'Werewolves': 'Lobos, *(abran sus ojos y miren los demás lobos.), seleccionen a quien matar.',
    'Wild Child': '*Chico Salvaje (Wild Child), selecciona tu rol a seguir.',
    'Witch': 'Bruja (Witch) despierta, (señala el jugador) este jugador ha muerto, lo revives? (uno por juego), matarás a alguien? (uno por juego).',
    'Wolf Man': '*Hombre lobo (Wolf Man) despierta.',
    'Wolverine': '*Guepardo (Wolverine), despierta.'
}